version: '3'
services:
  api:
    environment: # for a full list check the corresponding properties-builder file
      SPRING_DATA_MONGODB_HOST: "db"
      SPRING_DATA_MONGODB_PORT: "27017"
      SPRING_DATA_MONGODB_DATABASE: "dashboarddb"
      SPRING_DATA_MONGODB_USERNAME: "dashboarduser"
      SPRING_DATA_MONGODB_PASSWORD: "dbpassword"
      KEY: "4PtSqA7fH8T3p5hulIPH8gibtR+1FggI"
    volumes:
      - $PWD/hygieia/logs:/hygieia/logs

  api-audit:
    environment:
      SPRING_DATA_MONGODB_HOST: "db"
      SPRING_DATA_MONGODB_PORT: "27017"
      SPRING_DATA_MONGODB_DATABASE: "dashboarddb"
      SPRING_DATA_MONGODB_USERNAME: "dashboarduser"
      SPRING_DATA_MONGODB_PASSWORD: "dbpassword"
      KEY: "4PtSqA7fH8T3p5hulIPH8gibtR+1FggI"

  github-collector:
    environment:
      JASYPT_ENCRYPTOR_PASSWORD: "hygieiasecret"
      KEY: "4PtSqA7fH8T3p5hulIPH8gibtR+1FggI"
      GITHUB_KEY: "4PtSqA7fH8T3p5hulIPH8gibtR+1FggI"
      PERSONAL_ACCESS_TOKEN: "9ddc3d0982e6c21ed01af65c15406b018de14e1c"
      MONGODB_HOST: "db"
      MONGODB_PORT: "27017"
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE: "dashboarddb"
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME: "dashboarduser"
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD: "dbpassword" 

  jenkins-build-collector:
    environment:
      MONGODB_HOST: "db"
      MONGODB_PORT: "27017"
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE: "dashboarddb"
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME: "dashboarduser"
      HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD: "dbpassword"
