# Help: rename the adject docker-compose.override.example.yml file to docker-compose.override.yml
#       then in the override file uncomment the environment tag for the collectors you want to
#       run. Then add the environment vars you want to use.
version: '3'
services:
  proxy:
    build: proxy
    ports:
      - "80:80"
      - "443:443"

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"

  db-setup:
    build: db
    depends_on:
      - db

  api:
    build: api
    image: hygieia-api
    depends_on:
      - db-setup

  api-audit:
    build: api-audit
    image: hygieia-api-audit
    depends_on:
      - db-setup

  ui:
    build: UI
    image: hygieia-ui
    depends_on:
      - api

  jenkins:
    image: jenkinsci/jenkins
    depends_on:
      - api
    volumes:
      - "jenkins_data:/var/jenkins_home"

  github-collector:
    build: collectors/scm/github
    image: hygieia-github-scm-collector
    depends_on:
      - db-setup

  jenkins-build-collector:
    build: collectors/build/jenkins
    image: hygieia-jenkins-build-collector
    depends_on:
      - db-setup

volumes:
  db-data:
  certs:
  jenkins_data:

